#!/usr/bin/env bash
# install.sh — one-command install of the opencode-class-agents template
# (macOS / Linux) into opencode's global config directory.
#
# - Backs up any existing config at the target path.
# - Clones the public template, then re-inits it as a fresh local git repo.
# - Scaffolds canvas/.env (prompts for base URL + optional cookie) and
#   generates CONTEXT.md from CONTEXT.example.md.
# - Verifies the Canvas helper with `node canvas.mjs whoami`.
#
# Env overrides for scripted (non-interactive) installs:
#   CONFIG_DIR=/path        where to install (default: $HOME/.config/opencode)
#   SKIP_PROMPTS=1          skip all prompts, use defaults
#   INSTALL_OPENCODE=1      install opencode automatically if missing
#
# Example:
#   curl -fsSL https://raw.githubusercontent.com/DTA-Projects/opencode-class-agents/main/install.sh | bash
set -euo pipefail

REPO="https://github.com/DTA-Projects/opencode-class-agents.git"
CONFIG_DIR="${CONFIG_DIR:-$HOME/.config/opencode}"
SKIP_PROMPTS="${SKIP_PROMPTS:-0}"
INSTALL_OPENCODE="${INSTALL_OPENCODE:-0}"

say()   { printf '==> %s\n' "$*"; }
info()  { printf '    %s\n' "$*"; }
warn()  { printf '    WARNING: %s\n' "$*" >&2; }
done_() { printf '==> %s\n' "$*"; }

# Reads one line from the terminal even when the script is piped (curl | bash).
read_value() { # $1 = prompt ; sets REPLY
  REPLY=""
  [ "$SKIP_PROMPTS" = "1" ] && return
  if [ -e /dev/tty ]; then
    printf '%s' "$1" > /dev/tty
    IFS= read -r REPLY < /dev/tty || REPLY=""
    printf '\n' > /dev/tty
  fi
}

ask_yes() { # $1 = prompt ; exit 0 if yes
  if [ "$SKIP_PROMPTS" = "1" ]; then return 1; fi
  if [ -e /dev/tty ]; then
    printf '%s' "$1" > /dev/tty
    IFS= read -r REPLY < /dev/tty || REPLY="n"
    printf '\n' > /dev/tty
    case "$REPLY" in y|Y|yes|YES) return 0 ;; esac
  fi
  return 1
}

say "opencode-class-agents installer"

# ---- 1. Prerequisites ----------------------------------------------------
missing=""
if ! command -v git >/dev/null 2>&1; then missing="$missing git"; fi
if ! command -v node >/dev/null 2>&1; then missing="$missing node"; fi
if [ -n "$missing" ]; then
  warn "Missing required tools:$missing. Install them, then re-run."
  exit 1
fi

# ---- 2. opencode itself --------------------------------------------------
if ! command -v opencode >/dev/null 2>&1; then
  say "opencode is not installed"
  if [ "$INSTALL_OPENCODE" = "1" ] || ask_yes "Install opencode now via the official script? [y/N] "; then
    curl -fsSL https://opencode.ai/install | bash
  else
    info "Skipping. Install later with: curl -fsSL https://opencode.ai/install | bash"
  fi
fi

# ---- 3. Protect any existing config --------------------------------------
if [ -e "$CONFIG_DIR" ]; then
  if [ "$SKIP_PROMPTS" != "1" ] \
    && ! ask_yes "Existing config at $CONFIG_DIR. Back it up and replace? [y/N] "; then
    info "Aborted - nothing changed."
    exit 0
  fi
  backup="${CONFIG_DIR}.bak-$(date +%Y%m%d-%H%M%S)"
  say "Backing up existing config to $backup"
  mv "$CONFIG_DIR" "$backup"
else
  mkdir -p "$(dirname "$CONFIG_DIR")"
fi

# ---- 4. Clone the template, then re-init as a fresh repo -----------------
say "Cloning the template into $CONFIG_DIR"
git clone --quiet "$REPO" "$CONFIG_DIR"

say "Re-initializing your config as a fresh git repo"
rm -rf "$CONFIG_DIR/.git"
git -C "$CONFIG_DIR" init -b main >/dev/null 2>&1 || git -C "$CONFIG_DIR" init >/dev/null
git -C "$CONFIG_DIR" add -A
git -C "$CONFIG_DIR" commit -qm "Initial config from the opencode-class-agents template" \
  || warn "Could not create the initial commit. Check git config user.name and user.email."

# ---- 5. Canvas credentials ----------------------------------------------
say "Setting up Canvas credentials"
env_file="$CONFIG_DIR/canvas/.env"
base_url="https://your-school.instructure.com"
cookie=""
read_value "Canvas base URL (e.g. https://your-school.instructure.com) [${base_url}]: "
[ -n "$REPLY" ] && base_url="$REPLY"
read_value "Canvas session cookie  (paste now, or press Enter to add later): "
cookie="$REPLY"
cat > "$env_file" <<EOF
# Canvas credentials - generated by install.sh
# Get a fresh cookie: see docs/credentials.md in the template repo.
CANVAS_COOKIE=$cookie
CANVAS_API_BASE=$base_url

# Optional: use an API access token instead of a cookie (if your school allows it).
# CANVAS_API_TOKEN=
EOF
info "Wrote $env_file"

# ---- 6. CONTEXT.md (auto-loaded session context) --------------------------
if [ -f "$CONFIG_DIR/CONTEXT.example.md" ] && [ ! -f "$CONFIG_DIR/CONTEXT.md" ]; then
  cp "$CONFIG_DIR/CONTEXT.example.md" "$CONFIG_DIR/CONTEXT.md"
  info "Wrote $CONFIG_DIR/CONTEXT.md (edit it to match your setup)"
fi

# ---- 7. Textbooks folder --------------------------------------------------
textbooks="$HOME/Documents/++Textbooks"
if [ ! -e "$textbooks" ]; then
  mkdir -p "$textbooks"
  info "Created $textbooks - drop your textbook PDFs here"
fi

# ---- 8. Verify ------------------------------------------------------------
say "Verifying the Canvas helper"
if [ -n "$cookie" ]; then
  ( cd "$CONFIG_DIR/canvas" && node canvas.mjs whoami ) \
    || warn "whoami failed - check $env_file and re-run."
else
  info "Skipping whoami until you paste your cookie into $env_file"
fi

# ---- 9. Summary -----------------------------------------------------------
done_ "Install complete."
printf '%s\n' \
  "Next steps:" \
  "  1. Add your Canvas cookie if you skipped it: edit $env_file" \
  "  2. List your courses: cd $CONFIG_DIR/canvas && node canvas.mjs courses" \
  "     then copy the course ids into agents/*.md (see agents/template.md)" \
  "  3. Drop your textbooks into $textbooks" \
  "  4. (Recommended) Point this repo at your own private remote:" \
  "       gh repo create opencode-config --private --source=$CONFIG_DIR --push" \
  "  5. Restart opencode so it picks up the new config."